//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KikapWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public byte id { get; set; }
        public string authorName { get; set; }
        public Nullable<byte> bookPieces { get; set; }
        public string info { get; set; }
    }
}
