//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID { get; set; }
        public string bookName { get; set; }
        public string type { get; set; }
        public string author { get; set; }
        public string editor { get; set; }
        public Nullable<short> publicationDate { get; set; }
        public string publisher { get; set; }
        public Nullable<byte> edition { get; set; }
        public Nullable<double> price { get; set; }
        public string translator { get; set; }
        public Nullable<short> pageNumbers { get; set; }
        public string language { get; set; }
        public string size { get; set; }
        public string format_ { get; set; }
        public string ISBN { get; set; }
    }
}
