//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Books", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.Model")]
    [System.SerializableAttribute()]
    public partial class Books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bookNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> editionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string editorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string format_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> pageNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> publicationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string publisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string translatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookName {
            get {
                return this.bookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bookNameField, value) != true)) {
                    this.bookNameField = value;
                    this.RaisePropertyChanged("bookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> edition {
            get {
                return this.editionField;
            }
            set {
                if ((this.editionField.Equals(value) != true)) {
                    this.editionField = value;
                    this.RaisePropertyChanged("edition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string editor {
            get {
                return this.editorField;
            }
            set {
                if ((object.ReferenceEquals(this.editorField, value) != true)) {
                    this.editorField = value;
                    this.RaisePropertyChanged("editor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string format_ {
            get {
                return this.format_Field;
            }
            set {
                if ((object.ReferenceEquals(this.format_Field, value) != true)) {
                    this.format_Field = value;
                    this.RaisePropertyChanged("format_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> pageNumbers {
            get {
                return this.pageNumbersField;
            }
            set {
                if ((this.pageNumbersField.Equals(value) != true)) {
                    this.pageNumbersField = value;
                    this.RaisePropertyChanged("pageNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> publicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                if ((this.publicationDateField.Equals(value) != true)) {
                    this.publicationDateField = value;
                    this.RaisePropertyChanged("publicationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string publisher {
            get {
                return this.publisherField;
            }
            set {
                if ((object.ReferenceEquals(this.publisherField, value) != true)) {
                    this.publisherField = value;
                    this.RaisePropertyChanged("publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.sizeField, value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string translator {
            get {
                return this.translatorField;
            }
            set {
                if ((object.ReferenceEquals(this.translatorField, value) != true)) {
                    this.translatorField = value;
                    this.RaisePropertyChanged("translator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.Model")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string interestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sirnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tcNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string interested {
            get {
                return this.interestedField;
            }
            set {
                if ((object.ReferenceEquals(this.interestedField, value) != true)) {
                    this.interestedField = value;
                    this.RaisePropertyChanged("interested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sirname {
            get {
                return this.sirnameField;
            }
            set {
                if ((object.ReferenceEquals(this.sirnameField, value) != true)) {
                    this.sirnameField = value;
                    this.RaisePropertyChanged("sirname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tcNo {
            get {
                return this.tcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.tcNoField, value) != true)) {
                    this.tcNoField = value;
                    this.RaisePropertyChanged("tcNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orders", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.Model")]
    [System.SerializableAttribute()]
    public partial class Orders : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> bookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> customerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> orderCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> bookID {
            get {
                return this.bookIDField;
            }
            set {
                if ((this.bookIDField.Equals(value) != true)) {
                    this.bookIDField = value;
                    this.RaisePropertyChanged("bookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> customerID {
            get {
                return this.customerIDField;
            }
            set {
                if ((this.customerIDField.Equals(value) != true)) {
                    this.customerIDField = value;
                    this.RaisePropertyChanged("customerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> orderCount {
            get {
                return this.orderCountField;
            }
            set {
                if ((this.orderCountField.Equals(value) != true)) {
                    this.orderCountField = value;
                    this.RaisePropertyChanged("orderCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderDetail {
            get {
                return this.orderDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.orderDetailField, value) != true)) {
                    this.orderDetailField = value;
                    this.RaisePropertyChanged("orderDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IiService1")]
    public interface IiService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapGetir", ReplyAction="http://tempuri.org/IiService1/kitapGetirResponse")]
        WindowsFormsApplication1.ServiceReference1.Books[] kitapGetir(string deGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapGetir", ReplyAction="http://tempuri.org/IiService1/kitapGetirResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Books[]> kitapGetirAsync(string deGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapDetay", ReplyAction="http://tempuri.org/IiService1/kitapDetayResponse")]
        WindowsFormsApplication1.ServiceReference1.Books kitapDetay(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapDetay", ReplyAction="http://tempuri.org/IiService1/kitapDetayResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Books> kitapDetayAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapGuncelle", ReplyAction="http://tempuri.org/IiService1/kitapGuncelleResponse")]
        int kitapGuncelle(WindowsFormsApplication1.ServiceReference1.Books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapGuncelle", ReplyAction="http://tempuri.org/IiService1/kitapGuncelleResponse")]
        System.Threading.Tasks.Task<int> kitapGuncelleAsync(WindowsFormsApplication1.ServiceReference1.Books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapEkle", ReplyAction="http://tempuri.org/IiService1/kitapEkleResponse")]
        int kitapEkle(WindowsFormsApplication1.ServiceReference1.Books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapEkle", ReplyAction="http://tempuri.org/IiService1/kitapEkleResponse")]
        System.Threading.Tasks.Task<int> kitapEkleAsync(WindowsFormsApplication1.ServiceReference1.Books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapSil", ReplyAction="http://tempuri.org/IiService1/kitapSilResponse")]
        int kitapSil(WindowsFormsApplication1.ServiceReference1.Books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/kitapSil", ReplyAction="http://tempuri.org/IiService1/kitapSilResponse")]
        System.Threading.Tasks.Task<int> kitapSilAsync(WindowsFormsApplication1.ServiceReference1.Books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/musteriGetir", ReplyAction="http://tempuri.org/IiService1/musteriGetirResponse")]
        WindowsFormsApplication1.ServiceReference1.Customers[] musteriGetir(string deGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/musteriGetir", ReplyAction="http://tempuri.org/IiService1/musteriGetirResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Customers[]> musteriGetirAsync(string deGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/musteriDetay", ReplyAction="http://tempuri.org/IiService1/musteriDetayResponse")]
        WindowsFormsApplication1.ServiceReference1.Customers musteriDetay(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/musteriDetay", ReplyAction="http://tempuri.org/IiService1/musteriDetayResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Customers> musteriDetayAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/talepGetir", ReplyAction="http://tempuri.org/IiService1/talepGetirResponse")]
        WindowsFormsApplication1.ServiceReference1.Orders[] talepGetir(string deGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiService1/talepGetir", ReplyAction="http://tempuri.org/IiService1/talepGetirResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Orders[]> talepGetirAsync(string deGet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IiService1Channel : WindowsFormsApplication1.ServiceReference1.IiService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IiService1Client : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IiService1>, WindowsFormsApplication1.ServiceReference1.IiService1 {
        
        public IiService1Client() {
        }
        
        public IiService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IiService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IiService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IiService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApplication1.ServiceReference1.Books[] kitapGetir(string deGet) {
            return base.Channel.kitapGetir(deGet);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Books[]> kitapGetirAsync(string deGet) {
            return base.Channel.kitapGetirAsync(deGet);
        }
        
        public WindowsFormsApplication1.ServiceReference1.Books kitapDetay(int ID) {
            return base.Channel.kitapDetay(ID);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Books> kitapDetayAsync(int ID) {
            return base.Channel.kitapDetayAsync(ID);
        }
        
        public int kitapGuncelle(WindowsFormsApplication1.ServiceReference1.Books book) {
            return base.Channel.kitapGuncelle(book);
        }
        
        public System.Threading.Tasks.Task<int> kitapGuncelleAsync(WindowsFormsApplication1.ServiceReference1.Books book) {
            return base.Channel.kitapGuncelleAsync(book);
        }
        
        public int kitapEkle(WindowsFormsApplication1.ServiceReference1.Books book) {
            return base.Channel.kitapEkle(book);
        }
        
        public System.Threading.Tasks.Task<int> kitapEkleAsync(WindowsFormsApplication1.ServiceReference1.Books book) {
            return base.Channel.kitapEkleAsync(book);
        }
        
        public int kitapSil(WindowsFormsApplication1.ServiceReference1.Books book) {
            return base.Channel.kitapSil(book);
        }
        
        public System.Threading.Tasks.Task<int> kitapSilAsync(WindowsFormsApplication1.ServiceReference1.Books book) {
            return base.Channel.kitapSilAsync(book);
        }
        
        public WindowsFormsApplication1.ServiceReference1.Customers[] musteriGetir(string deGet) {
            return base.Channel.musteriGetir(deGet);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Customers[]> musteriGetirAsync(string deGet) {
            return base.Channel.musteriGetirAsync(deGet);
        }
        
        public WindowsFormsApplication1.ServiceReference1.Customers musteriDetay(int id) {
            return base.Channel.musteriDetay(id);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Customers> musteriDetayAsync(int id) {
            return base.Channel.musteriDetayAsync(id);
        }
        
        public WindowsFormsApplication1.ServiceReference1.Orders[] talepGetir(string deGet) {
            return base.Channel.talepGetir(deGet);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Orders[]> talepGetirAsync(string deGet) {
            return base.Channel.talepGetirAsync(deGet);
        }
    }
}
